title: "FKIE Cyber Analysis & Defense (CA&D)"
description: "Cyber Analysis & Defense (CA&D) department's open source projects"
theme: jekyll-theme-slate
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
